# Generated by Django 2.1.15 on 2023-02-27 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_v2", "0012_auto_20220626_1402"),
    ]

    operations = [
        migrations.CreateModel(
            name="PokemonStatPast",
            fields=[
                (
                    "id",
                    models.AutoField(
                        verbose_name="ID",
                        serialize=False,
                        auto_created=True,
                        primary_key=True,
                    ),
                ),
                ("base_stat", models.IntegerField()),
                #("effort", models.IntegerField()),
                (
                    "pokemon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pokemonstatpast",
                        to="pokemon_v2.Pokemon",
                    ),
                ),
                (
                    "generation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pokemonstatpast",
                        to="pokemon_v2.Generation",
                    ),
                ),
                (
                    "stat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pokemonstatpast",
                        to="pokemon_v2.Stat",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]